version: "3.8"
services:
  classifier:
    build:
      context: ./Automated-Question-classify
      dockerfile: Dockerfile
    image: mcq-classifier
    ports:
      - "8000:8000"

  web:
    build:
      context: ./latex-mcq
      dockerfile: Dockerfile
    image: mcq-web
    ports:
      - "3000:3000"