services:
  mongodb:
    image: mongo:latest
    container_name: mcq-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: mcq-app
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mcq-database?authSource=admin
      - SESSION_SECRET=${SESSION_SECRET}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    restart: unless-stopped

volumes:
  mongodb_data: