services:
  # Python Classifier Service
  - type: web
    name: mcq-classifier
    runtime: docker
    repo: https://github.com/SreekarMallela2512/Integrated-Latex_mcq.git # Replace with your repo
    rootDir: Automated-Question-classify
    dockerfilePath: ./Dockerfile
    plan: free # or "starter" for paid plan
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_ENV
        value: production
    healthCheckPath: /health # Add a health check endpoint in your app

  # Node.js Web Service
  - type: web
    name: mcq-latex-web
    runtime: docker
    repo: https://github.com/SreekarMallela2512/Integrated-Latex_mcq.git # Replace with your repo
    rootDir: latex-mcq
    dockerfilePath: ./Dockerfile
    plan: free # or "starter" for paid plan
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: CLASSIFIER_URL
        value: https://mcq-classifier.onrender.com # Will be the URL of your classifier service
    healthCheckPath: /health # Add a health check endpoint in your app